version: '2'
services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - "../:/srv/app"
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
    labels:
      name: "Web Server"
    depends_on:
      - php

  php:
    build:
        context: ./php
        dockerfile: Dockerfile
    volumes:
      - "../:/srv/app"
    ports:
      - "9000"
    working_dir: "/srv/app"
    environment:
      PHP_IDE_CONFIG: "serverName=APP"

  mysql-test:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    ports:
      - "3306:3306"
    labels:
      name: "Test Database"
    volumes:
      - "./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql"
      - "./mysql/my.cnf:/etc/mysql/my.cnf:ro"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: app_test